FROM node:lts-bookworm
ENV PATH="/usr/local/bin:/root/.local/bin/:$PATH"
WORKDIR /app
RUN apt-get update && apt-get clean && apt-get install -y build-essential
RUN apt-get install curl tmux jq gcc g++ -y
RUN npm i -g bun tsx pm2@latest
RUN apt-get install -y python3-dev python3-pip-whl python3-setuptools-whl python3-venv
RUN apt-get install -y --no-install-recommends git openssh-client

# === INSTALL uv ===
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

