FROM node:23.1-bookworm-slim
ENV PATH="/usr/local/bin:$PATH"
WORKDIR /app
RUN apt-get update
RUN apt install python3-dev python3-pip python3-venv gcc g++ -y
RUN apt install curl tmux jq -y
RUN npm i -g bun pm2
